apiVersion: v1
kind: ResourceQuota
metadata:
  name: travelo-resource-quota
  namespace: travelo
spec:
  hard:
    requests.cpu: "2"
    requests.memory: 2Gi
    limits.cpu: "4"
    limits.memory: 4Gi
    pods: "12"
    services: "10"
    persistentvolumeclaims: "4"

