apiVersion: v1
kind: Secret
metadata:
  name: travelo-secret
  namespace: travelo
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: password
  MYSQL_PASSWORD: travelo123
  SPRING_DATASOURCE_PASSWORD: travelo123

